name: spelling-preprocessing-ru
endpoints:
- respond
compose:
  env_file:
  - .env_ru
  build:
    args:
      CONFIG: levenshtein_corrector_ru.json
      SERVICE_PORT: 8074
      SRC_DIR: annotators/spelling_preprocessing_dp
      COMMIT: f5117cd9ad1e64f6c2d970ecaa42fc09ccb23144
      LANGUAGE: RU
      FLASK_APP: server
    context: ./
    dockerfile: annotators/spelling_preprocessing_dp/Dockerfile
  command: flask run -h 0.0.0.0 -p 8074
  environment:
  - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 8G
      reservations:
        memory: 8G
  volumes:
  - ./annotators/spelling_preprocessing_dp:/src
  - ~/.deeppavlov:/root/.deeppavlov
  ports:
  - 8074:8074
proxy: null
