# С такими volumes удобно дебажить, не нужно пересобирать контейнер каждый раз при изменении кода
services:
  agent:
    volumes:
      - ".:/dp-agent"
    ports:
      - 4242:4242
  sentseg:
    volumes:
      - "./annotators/SentSeg:/src"
    ports:
      - 8011:8011
  ranking-based-response-selector:
    volumes:
      - "./response_selectors/ranking_based_response_selector:/src"
      - "./common:/src/common"
    ports:
      - 8002:8002
  mongo:
    ports:
      - 27017:27017
    # # you can use persistent local volume if you need
    # volumes:
    #   - ./venv/data/db_data:/root/data/db
  combined-classification:
    volumes:
      - "./common:/src/common"
      - "./annotators/combined_classification:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8087:8087
  openai-api-chatgpt:
    volumes:
      - "./services/openai_api_lm:/src"
      - "./common:/src/common"
    ports:
      - 8145:8145
  dff-reasoning-skill:
    volumes:
      - "./skills/dff_reasoning_skill:/src"
      - "./common:/src/common"
      - "./skills/dff_weather_skill/tools:/src/tools"
      - "./skills/dff_weather_skill/data:/src/data"
    ports:
      - 8169:8169
  sentence-ranker:
    volumes:
      - "./services/sentence_ranker:/src"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8128:8128

version: "3.7"