services:
  agent:
    volumes:
      - "/cephfs/home/ignatov/artifacts:/output"
    ports:
      - ${AGENT_PORT}:4242
  combined-classification:
    volumes:
      - "./common:/src/common"
      - "./annotators/combined_classification:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    environment:
      - CUDA_VISIBLE_DEVICES=7
  mongo:
    command: mongod
    image: mongo:4.0.0
    # # you can use persistent local volume if you need
    # volumes:
    #   - ./venv/data/db_data:/root/data/db
  sentseg:
    volumes:
      - "./annotators/SentSeg:/src"
  sentence-ranker:
    volumes:
      - "~/.deeppavlov/cache:/root/.cache"
    environment:
      - CUDA_VISIBLE_DEVICES=9
  dff-reasoning-skill:
    volumes:
      - "./skills/dff_reasoning_skill:/src"
      - "./common:/src/common"
      - "./skills/dff_weather_skill/tools:/src/tools"
      - "./skills/dff_weather_skill/data:/src/data"
version: '3.7'
