SERVICE_PORT: 8132
SERVICE_NAME: gpt2_generator
CONFIG_NAME: mgpt.json
PRETRAINED_MODEL_NAME_OR_PATH: sberbank-ai/mGPT
N_HYPOTHESES_TO_GENERATE: 3
MAX_HISTORY_DEPTH: 3
CUDA_VISIBLE_DEVICES: '0'
FLASK_APP: server
