name: asr
endpoints:
- asr_check
compose:
  env_file:
  - .env
  build:
    context: .
    dockerfile: ./annotators/asr/Dockerfile
  command: flask run -h 0.0.0.0 -p 8031
  environment:
  - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 100M
      reservations:
        memory: 100M
  volumes:
  - ./annotators/asr:/src
  - ./common:/src/common
  ports:
  - 8031:8031
