name: dff-bot-persona-skill
endpoints:
- respond
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8105
      SERVICE_NAME: dff_bot_persona_skill
    context: .
    dockerfile: ./skills/dff_bot_persona_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8105
  deploy:
    resources:
      limits:
        memory: 256M
      reservations:
        memory: 256M
  volumes:
  - ./skills/dff_bot_persona_skill:/src
  - ./common:/src/common
  ports:
  - 8105:8105
