SERVICE_PORT: 8125
SERVICE_NAME: dialogpt
PRETRAINED_MODEL_NAME_OR_PATH: microsoft/DialoGPT-medium
N_HYPOTHESES_TO_GENERATE: 5
CONFIG_NAME: dialogpt_en.json
MAX_HISTORY_DEPTH: 2
CUDA_VISIBLE_DEVICES: '0'
FLASK_APP: server
