SERVICE_PORT: 8175
SERVICE_NAME: dff_official_letter_ru_prompted_skill
PROMPT_FILE: common/prompts/official_letter_ru.json
GENERATIVE_SERVICE_URL: http://transformers-lm-ruxglm:8171/respond
GENERATIVE_SERVICE_CONFIG: ruxglm_config.json
GENERATIVE_TIMEOUT: 20
N_UTTERANCES_CONTEXT: 3
