name: dff-dream-persona-gpt-j-prompted-skill
endpoints:
- respond
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8134
      SERVICE_NAME: dff_dream_persona_prompted_skill
      PROMPT_FILE: common/prompts/dream_persona.json
      GENERATIVE_SERVICE_URL: http://transformers-lm-gptjt:8161/respond
      GENERATIVE_SERVICE_CONFIG: default_generative_config.json
      GENERATIVE_TIMEOUT: 120
      N_UTTERANCES_CONTEXT: 7
    context: .
    dockerfile: ./skills/dff_template_prompted_skill/Dockerfile
  deploy:
    resources:
      limits:
        memory: 128M
      reservations:
        memory: 128M
  volumes:
  - ./skills/dff_template_prompted_skill:/src
  - ./common:/src/common
  ports:
  - 8134:8134
proxy: null
