name: entity-linking-deepy
endpoints:
- model
compose:
  build:
    args:
      SERVICE_PORT: 8075
      SERVICE_NAME: entity_linking
      CONFIG: entity_linking_deepy.json
      SRC_DIR: annotators/entity_linking_deepy
      CUDA_VISIBLE_DEVICES: ''''''
    context: ./
    dockerfile: annotators/entity_linking_deepy/Dockerfile
  volumes:
  - ~/.deeppavlov:/root/.deeppavlov
  ports:
  - 8075:8075
  environment:
  - CUDA_VISIBLE_DEVICES=''
proxy: null
