name: dff-intent-responder-ru-skill
endpoints:
- respond
compose:
  env_file:
  - .env_ru
  build:
    args:
      SERVICE_PORT: 8012
      SERVICE_NAME: dff_intent_responder_skill
      INTENT_RESPONSE_PHRASES_FNAME: intent_response_phrases_RU.json
      LANGUAGE: RU
    context: .
    dockerfile: ./skills/dff_intent_responder_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8012 --reload
  deploy:
    resources:
      limits:
        memory: 128M
      reservations:
        memory: 128M
  volumes:
  - ./skills/dff_intent_responder_skill:/src
  - ./common:/src/common
  ports:
  - 8012:8012
proxy: null
