name: dff-art-skill
endpoints:
- respond
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8117
      SERVICE_NAME: dff_art_skill
    context: .
    dockerfile: ./skills/dff_art_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8117
  deploy:
    resources:
      limits:
        memory: 512M
      reservations:
        memory: 512M
  volumes:
  - ./skills/dff_art_skill:/src
  - ./common:/src/common
  ports:
  - 8117:8117
