name: fact-random
endpoints:
- respond
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8119
      SERVICE_NAME: fact_random
      FLASK_APP: server
    context: .
    dockerfile: ./annotators/fact_random/Dockerfile
  command: flask run -h 0.0.0.0 -p 8119
  environment:
  - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 256M
      reservations:
        memory: 256M
  volumes:
  - ./annotators/fact_random:/src
  - ./common:/src/common
  ports:
  - 8119:8119
