name: personality-catcher
endpoints:
- personality_catcher
compose:
  env_file:
  - .env
  build:
    context: ./skills/personality_catcher/
  command: uvicorn server:app --host 0.0.0.0 --port 8010
  deploy:
    resources:
      limits:
        memory: 100M
      reservations:
        memory: 100M
  volumes:
  - ./skills/personality_catcher:/app
  ports:
  - 8010:8010
