services:
  agent:
    volumes:
      - "/cephfs/home/ignatov/artifacts:/output"
    ports:
      - ${AGENT_PORT}:4242
  mongo:
    command: mongod
    image: mongo:4.0.0
  files:
    volumes:
      - "~/.deeppavlov/file_server:/tmp"
  ranking-based-response-selector:
    volumes:
      - "./response_selectors/ranking_based_response_selector:/src"
      - "./common:/src/common"
  combined-classification:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    environment:
      - CUDA_VISIBLE_DEVICES=8
  sentseg:
  sentence-ranker:
    volumes:
      - "./services/sentence_ranker:/src"
      - "~/.deeppavlov/cache:/root/.cache"
    environment:
      - CUDA_VISIBLE_DEVICES=7
  openai-api-chatgpt:
    volumes:
      - "./services/openai_api_lm:/src"
      - "./common:/src/common"
  doc-retriever:
    volumes:
      - "./annotators/doc_retriever:/src"
      - "./common:/src/common"
      - "./documents:/src/documents"
  dff-document-qa-llm-skill:
    volumes:
      - "./skills/dff_document_qa_llm_skill:/src"
      - "./common:/src/common"
      - "./documents:/src/documents"

version: "3.7"
