name: dff-dream-faq-prompted-skill
endpoints:
- respond
compose:
  env_file:
  - .env,.env_secret
  build:
    args:
      SERVICE_PORT: 8170
      SERVICE_NAME: dff_dream_faq_prompted_skill
      PROMPT_FILE: common/prompts/dream_faq.json
      GENERATIVE_SERVICE_URL: http://openai-api-chatgpt-16k:8167/respond
      GENERATIVE_SERVICE_CONFIG: openai-chatgpt.json
      GENERATIVE_TIMEOUT: 120
      N_UTTERANCES_CONTEXT: 7
      ENVVARS_TO_SEND: OPENAI_API_KEY,OPENAI_ORGANIZATION
    context: .
    dockerfile: ./skills/dff_template_prompted_skill/Dockerfile
  deploy:
    resources:
      limits:
        memory: 128M
      reservations:
        memory: 128M
  volumes:
  - ./skills/dff_template_prompted_skill:/src
  - ./common:/src/common
  ports:
  - 8170:8170
proxy: null
