SERVICE_PORT: 8013
SERVICE_NAME: toxic_classification
PRETRAINED_MODEL_NAME_OR_PATH: https://github.com/unitaryai/detoxify/releases/download/v0.4-alpha/multilingual_debiased-0b549669.ckpt
CUDA_VISIBLE_DEVICES: '0'
FLASK_APP: server
