SERVICE_PORT: 8135
SERVICE_NAME: prompt_selector
SENTENCE_RANKER_SERVICE_URL: http://sentence-ranker:8128/respond
N_SENTENCES_TO_RETURN: 2
PROMPTS_TO_CONSIDER: dream_persona,casual_email,meeting_notes,official_email,plan_for_article
FLASK_APP: server
