# С такими volumes удобно дебажить, не нужно пересобирать контейнер каждый раз при изменении кода
services:
  agent:
    volumes:
      - ".:/dp-agent"
    ports:
      - 4242:4242
  midas-classification:
    volumes:
      - "./annotators/midas_classification:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8090:8090
  sentseg:
    volumes:
      - "./annotators/SentSeg:/src"
    ports:
      - 8011:8011
  convers-evaluation-selector:
    volumes:
      - "./response_selectors/convers_evaluation_based_selector:/src"
      - "./common:/src/common"
    ports:
      - 8009:8009
  dff-intent-responder-skill:
    volumes:
      - "./skills/dff_intent_responder_skill:/src"
      - "./common:/src/common"
    ports:
      - 8012:8012
  intent-catcher:
    volumes:
      - "./annotators/IntentCatcherTransformers:/src"
      - "./common:/src/common"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8014:8014
  badlisted-words:
    volumes:
      - "./annotators/BadlistedWordsDetector:/src"
      - "./common:/src/common"
    ports:
      - 8018:8018
  spelling-preprocessing:
    volumes:
      - "./annotators/spelling_preprocessing:/src"
    ports:
      - 8074:8074
  dialogpt:
    volumes:
      - "./services/dialogpt:/src"
      - "./common:/src/common"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8125:8125
  sentence-ranker:
    volumes:
      - "./services/sentence_ranker:/src"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8128:8128
  seq2seq-persona-based:
    volumes:
      - "./services/seq2seq_persona_based:/src"
      - "./common:/src/common"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8140:8140
  relative-persona-extractor:
    volumes:
      - "./annotators/relative_persona_extractor:/src"
      - "./common:/src/common"
    ports:
      - 8133:8133
version: "3.7"
