# С такими volumes удобно дебажить, не нужно пересобирать контейнер каждый раз при изменении кода
services:
  agent:
    volumes:
      - ".:/dp-agent"
    ports:
      - 4242:4242

  sentseg:
    volumes:
      - "./annotators/SentSeg:/src"
    ports:
      - 8011:8011
  ranking-based-response-selector:
    volumes:
      - "./response_selectors/ranking_based_response_selector:/src"
      - "./common:/src/common"
    ports:
      - 8002:8002
  dff-intent-responder-skill:
    volumes:
      - "./skills/dff_intent_responder_skill:/src"
      - "./common:/src/common"
    ports:
      - 8012:8012
  dff-command-selector-skill:
    volumes:
      - "./skills/dff_command_selector_skill:/src"
      - "./common:/src/common"
    ports:
      - 8148:8148
  intent-catcher-commands:
    volumes:
      - "./annotators/IntentCatcherTransformers:/src"
      - "./common:/src/common"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8014:8014
  ner:
    volumes:
      - './annotators/NER_deeppavlov:/src'
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8021:8021
  mongo:
    ports:
      - 27017:27017
    # # you can use persistent local volume if you need
    # volumes:
    #   - ./venv/data/db_data:/root/data/db
  combined-classification:
    volumes:
      - "./common:/src/common"
      - "./annotators/combined_classification:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8087:8087
  entity-detection:
    volumes:
      - "./annotators/entity_detection:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8103:8103
  sentence-ranker:
    volumes:
      - "./services/sentence_ranker:/src"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8128:8128
  prompt-selector:
    volumes:
      - "./annotators/prompt_selector:/src"
      - "./common:/src/common"
    ports:
      - 8135:8135
  openai-api-chatgpt:
    volumes:
      - "./services/openai_api_lm:/src"
      - "./common:/src/common"
    ports:
      - 8145:8145
  dff-dream-persona-chatgpt-prompted-skill:
    volumes:
      - "./skills/dff_template_prompted_skill:/src"
      - "./common:/src/common"
    ports:
      - 8137:8137
  dff-google-api-skill:
    volumes:
      - "./skills/dff_google_api_skill:/src"
      - "./common:/src/common"
    ports:
      - 8162:8162
  openai-api-chatgpt-16k:
    volumes:
      - "./services/openai_api_lm:/src"
      - "./common:/src/common"
    ports:
      - 8167:8167
  robot-command-sender:
    volumes:
      - "./services/robot_command_sender:/src"
      - "./common:/src/common"
    ports:
      - 8035:8035
  robot-notifications:
    volumes:
      - "./services/robot_notifications:/src"
      - "./common:/src/common"
    ports:
      - 8036:8036
  robot-fake-server:
    volumes:
      - "./services/robot_fake_server:/src"
      - "./common:/src/common"
    ports:
      - 8038:8038

version: "3.7"
