name: combined-classification-lightweight
endpoints:
- model
- batch_model
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8150
      SERVICE_NAME: combined_classification
      CONFIG: combined_classifier.json
      CUDA_VISIBLE_DEVICES: ''
    context: .
    dockerfile: ./annotators/combined_classification_lightweight/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8150 --timeout 600
  environment:
  - CUDA_VISIBLE_DEVICES=0
  deploy:
    resources:
      limits:
        memory: 2G
      reservations:
        memory: 2G
  volumes:
  - ./common:/src/common
  - ./annotators/combined_classification_lightweight:/src
  - ~/.deeppavlov:/root/.deeppavlov
  - ~/.deeppavlov/cache:/root/.cache
  ports:
  - 8150:8150
