name: dff-travel-skill
endpoints:
- respond
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8096
      SERVICE_NAME: dff_travel_skill
    context: .
    dockerfile: skills/dff_travel_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8096
  deploy:
    resources:
      limits:
        memory: 768M
      reservations:
        memory: 768M
  volumes:
  - ./skills/dff_travel_skill:/src
  - ./common:/src/common
  ports:
  - 8096:8096
