# С такими volumes удобно дебажить, не нужно пересобирать контейнер каждый раз при изменении кода
services:
  agent:
    volumes:
      - ".:/dp-agent"
    ports:
      - 4242:4242
  dff-program-y-ru-skill:
    volumes:
      - "./skills/dff_program_y_skill:/src"
      - "./common:/src/common"
    ports:
      - 8008:8008
  convers-evaluation-selector-ru:
    volumes:
      - "./response_selectors/convers_evaluation_based_selector:/src"
      - "./common:/src/common"
    ports:
      - 8009:8009
  dff-intent-responder-ru-skill:
    volumes:
      - "./skills/dff_intent_responder_skill:/src"
      - "./common:/src/common"
    ports:
      - 8012:8012
  sentseg-ru:
    volumes:
      - "./annotators/sentseg_ru:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8011:8011
  intent-catcher-ru:
    volumes:
      - "./annotators/IntentCatcherTransformers:/src"
      - "./common:/src/common"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8014:8014
  badlisted-words-ru:
    volumes:
      - "./annotators/BadlistedWordsDetector_ru:/src"
      - "./common:/src/common"
    ports:
      - 8018:8018
  toxic-classification-ru:
    volumes:
      - "./annotators/toxic_classification_ru:/src"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8118:8118
  ner-ru:
    volumes:
      - './annotators/NER_deeppavlov:/src'
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8021:8021
  personal-info-ru-skill:
    volumes:
      - "./skills/personal_info_skill:/src"
      - "./common:/src/common"
    ports:
      - 8030:8030
  entity-linking-ru:
    volumes:
      - "./annotators/entity_linking_rus:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8075:8075
  wiki-parser-ru:
    volumes:
      - "./annotators/wiki_parser:/src"
      - "./common:/src/common"
    ports:
      - 8077:8077
  mongo:
    ports:
      - 27017:27017
    # # you can use persistent local volume if you need
    # volumes:
    #   - ./venv/data/db_data:/root/data/db
  spelling-preprocessing-ru:
    volumes:
      - "./annotators/spelling_preprocessing_dp:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8074:8074
  spacy-annotator-ru:
    volumes:
      - "./annotators/spacy_annotator:/src"
    ports:
      - 8129:8129
  dff-friendship-ru-skill:
    volumes:
      - "./skills/dff_friendship_skill:/src"
      - "./common:/src/common"
    ports:
      - 8086:8086
  entity-detection-ru:
    volumes:
      - "./annotators/entity_detection_rus:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8103:8103
  dialogpt-ru:
    volumes:
      - "./services/dialogpt_RU:/src"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8125:8125
  dff-generative-ru-skill:
    volumes:
      - "./skills/dff_generative_skill:/src"
      - "./common:/src/common"
    ports:
      - 8092:8092
  dialogrpt-ru:
    volumes:
      - "./services/dialogrpt_ru:/src"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8122:8122
  dff-template-skill:
    volumes:
      - "./skills/dff_template_skill:/src"
      - "./common:/src/common"
    ports:
      - 8120:8120
  fact-retrieval-ru:
    volumes:
      - "./annotators/fact_retrieval_rus:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8110:8110
  text-qa-ru:
    volumes:
      - "./services/text_qa:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8078:8078
  summarization-annotator:
    volumes:
      - "./annotators/summarization_annotator:/src"
    ports:
      - 8058:8058
  rut5-summarizer:
    volumes:
      - "./services/ruT5_summarizer:/src"
    ports:
      - 8060:8060
version: "3.7"
