services:
  agent:
    volumes:
      - "/cephfs/home/ignatov/artifacts:/output"
    ports:
      - ${AGENT_PORT}:4242
  mongo:
    command: mongod
    image: mongo:4.0.0
  dff-program-y-ru-skill:
  convers-evaluation-selector-ru:
  dff-intent-responder-ru-skill:
  dff-generative-ru-skill:
  intent-catcher-ru:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
    environment:
      - CUDA_VISIBLE_DEVICES=8
  badlisted-words-ru:
  toxic-classification-ru:
    volumes:
      - "~/.deeppavlov/cache:/root/.cache"
    environment:
      - CUDA_VISIBLE_DEVICES=7
  ner-ru:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
    environment:
      - CUDA_VISIBLE_DEVICES=8
  personal-info-ru-skill:
  entity-linking-ru:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
  wiki-parser-ru:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
  spelling-preprocessing-ru:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
  dff-friendship-ru-skill:
  entity-detection-ru:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
  sentseg-ru:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
    environment:
      - CUDA_VISIBLE_DEVICES=7
  dialogpt-ru:
    volumes:
      - "~/.deeppavlov/cache:/root/.cache"
    environment:
      - CUDA_VISIBLE_DEVICES=6
  dialogrpt-ru:
    volumes:
      - "~/.deeppavlov/cache:/root/.cache"
    environment:
      - CUDA_VISIBLE_DEVICES=6
  dff-template-skill:
  fact-retrieval-ru:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
    environment:
      - CUDA_VISIBLE_DEVICES=5
  text-qa-ru:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
    environment:
      - CUDA_VISIBLE_DEVICES=5
version: '3.7'
