services:
  agent:
    volumes:
      - "/cephfs/home/ignatov/artifacts:/output"
    ports:
      - ${AGENT_PORT}:4242
  mongo:
    command: mongod
    image: mongo:4.0.0
  gpt2-multilingual:
    environment:
      - CUDA_VISIBLE_DEVICES=6
  toxic-classification-multilingual:
    environment:
      - CUDA_VISIBLE_DEVICES=8
  sentiment-classification-multilingual:
    environment:
      - CUDA_VISIBLE_DEVICES=8
  sentence-ranker-multilingual:
    environment:
      - CUDA_VISIBLE_DEVICES=7

version: '3.7'
