SERVICE_PORT: 8146
SERVICE_NAME: dff_deeppavlov_prompted_skill
PROMPT_FILE: common/prompts/deeppavlov.json
GENERATIVE_SERVICE_URL: http://openai-api-chatgpt:8145/respond
GENERATIVE_SERVICE_CONFIG: openai-chatgpt.json
GENERATIVE_TIMEOUT: 120
N_UTTERANCES_CONTEXT: 7
ENVVARS_TO_SEND: OPENAI_API_KEY,OPENAI_ORGANIZATION
ALLOW_PROMPT_RESET: 1
