name: dff-gossip-skill
endpoints:
- respond
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8109
      SERVICE_NAME: dff_gossip_skill
    context: .
    dockerfile: skills/dff_gossip_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8109
  deploy:
    resources:
      limits:
        memory: 256M
      reservations:
        memory: 256M
  volumes:
  - ./skills/dff_gossip_skill:/src
  - ./common:/src/common
  ports:
  - 8109:8109
