SERVICE_NAME: entity_detection
SEQ_TAG_CONFIG: wikipedia_entity_detection_distilbert.json
CONFIG: entity_detection_eng.json
LOWERCASE: 1
SERVICE_PORT: 8103
SRC_DIR: annotators/entity_detection/
FINEGRAINED: 0
FLASK_APP: server
CUDA_VISIBLE_DEVICES: '0'
