SERVICE_PORT: 8135
SERVICE_NAME: prompt_selector
SENTENCE_RANKER_SERVICE_URL: http://dialogrpt-ru:8122/rank_sentences
N_SENTENCES_TO_RETURN: 3
PROMPTS_TO_CONSIDER: official_letter_ru,informal_letter_ru,journalist_helper_ru
FLASK_APP: server