name: dff-meeting-notes-prompted-skill
endpoints:
- respond
compose:
  env_file:
  - .env
  - .env_secret
  build:
    args:
      SERVICE_PORT: 8155
      SERVICE_NAME: dff_meeting_notes_prompted_skill
      PROMPT_FILE: common/prompts/meeting_notes.json
      GENERATIVE_SERVICE_URL: http://openai-api-davinci3:8131/respond
      GENERATIVE_SERVICE_CONFIG: openai-text-davinci-003-long.json
      GENERATIVE_TIMEOUT: 120
      N_UTTERANCES_CONTEXT: 7
      ENVVARS_TO_SEND: OPENAI_API_KEY,OPENAI_ORGANIZATION
    context: .
    dockerfile: ./skills/dff_template_prompted_skill/Dockerfile
  deploy:
    resources:
      limits:
        memory: 128M
      reservations:
        memory: 128M
  volumes:
  - ./skills/dff_template_prompted_skill:/src
  - ./common:/src/common
  ports:
  - 8155:8155
proxy: null
