name: dff-intent-responder-skill
endpoints:
- respond
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8012
      SERVICE_NAME: dff_intent_responder_skill
      INTENT_RESPONSE_PHRASES_FNAME: intent_response_phrases.json
    context: .
    dockerfile: ./skills/dff_intent_responder_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8012 --reload
  deploy:
    resources:
      limits:
        memory: 128M
      reservations:
        memory: 128M
  volumes:
  - ./skills/dff_intent_responder_skill:/src
  - ./common:/src/common
  ports:
  - 8012:8012
proxy:
  command:
  - nginx
  - -g
  - daemon off;
  build:
    context: dp/proxy/
    dockerfile: Dockerfile
  environment:
  - PROXY_PASS=dream.deeppavlov.ai:8012
  - PORT=8012
