SERVICE_PORT: 8140
SERVICE_NAME: seq2seq_persona_based
PRETRAINED_MODEL_NAME_OR_PATH: DeepPavlov/bart-base-en-persona-chat
PAIR_DIALOG_HISTORY_LENGTH: 2
CHAT_EVERY_SENT_MAX_LENGTH: 25
PERSONA_EVERY_SENT_MAX_LENGTH: 19
GENERATION_PARAMS_CONFIG: bart-base-en-persona-chat_v1.json
CUDA_VISIBLE_DEVICES: '0'
FLASK_APP: server
