name: masked-lm
endpoints:
- respond
compose:
  env_file:
  - .env
  build:
    context: ./services/masked_lm/
    args:
      SERVICE_PORT: 8102
      SERVICE_NAME: masked_lm
      PRETRAINED_MODEL_NAME_OR_PATH: bert-base-uncased
      CUDA_VISIBLE_DEVICES: '0'
      FLASK_APP: server
  command: flask run -h 0.0.0.0 -p 8102
  environment:
  - CUDA_VISIBLE_DEVICES=0
  - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 4G
      reservations:
        memory: 4G
  volumes:
  - ./services/masked_lm:/src
  - ./common:/src/common
  - ~/.deeppavlov/cache:/root/.cache
  ports:
  - 8102:8102
proxy: null
