SERVICE_PORT: 8153
SERVICE_NAME: dff_deepy_faq_prompted_skill
PROMPT_FILE: common/prompts/deepy_faq.json
GENERATIVE_SERVICE_URL: http://openai-api-davinci3:8131/respond
GENERATIVE_SERVICE_CONFIG: openai-text-davinci-003-long.json
GENERATIVE_TIMEOUT: 120
N_UTTERANCES_CONTEXT: 7
ENVVARS_TO_SEND: OPENAI_API_KEY,OPENAI_ORGANIZATION
