name: eliza
endpoints:
- respond
compose:
  env_file:
  - .env
  build:
    context: ./skills/eliza/
  command: flask run -h 0.0.0.0 -p 8047
  environment:
  - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 100M
      reservations:
        memory: 100M
  volumes:
  - ./skills/eliza:/src
  ports:
  - 8047:8047
