SERVICE_PORT: 8177
SERVICE_NAME: dff_journalist_helper_ru_prompted_skill
PROMPT_FILE: common/prompts/journalist_helper_ru.json
GENERATIVE_SERVICE_URL: http://transformers-lm-rugpt35:8178/respond
GENERATIVE_SERVICE_CONFIG: rugpt35_config.json
GENERATIVE_TIMEOUT: 20
N_UTTERANCES_CONTEXT: 3
