# С такими volumes удобно дебажить, не нужно пересобирать контейнер каждый раз при изменении кода
services:
  agent:
    volumes:
      - ".:/dp-agent"
    ports:
      - 4242:4242
  sentseg:
    volumes:
      - "./annotators/SentSeg:/src"
    ports:
      - 8011:8011
  llm-based-response-selector:
    volumes:
      - "./response_selectors/llm_based_response_selector:/src"
      - "./common:/src/common"
    ports:
      - 8003:8003
  combined-classification:
    volumes:
      - "./common:/src/common"
      - "./annotators/combined_classification:/src"
    ports:
      - 8087:8087
  sentence-ranker:
    volumes:
      - "./services/sentence_ranker:/src"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8128:8128
  prompt-selector:
    volumes:
      - "./annotators/prompt_selector:/src"
      - "./common:/src/common"
    ports:
      - 8135:8135
  openai-api-chatgpt:
    volumes:
      - "./services/openai_api_lm:/src"
      - "./common:/src/common"
    ports:
      - 8145:8145
  dff-dream-persona-chatgpt-prompted-skill:
    volumes:
      - "./skills/dff_template_prompted_skill:/src"
      - "./common:/src/common"
    ports:
      - 8137:8137
  dff-google-api-skill:
    volumes:
      - "./skills/dff_google_api_skill:/src"
      - "./common:/src/common"
    ports:
      - 8162:8162
  dff-dream-faq-prompted-skill:
    volumes:
      - "./skills/dff_template_prompted_skill:/src"
      - "./common:/src/common"
    ports:
      - 8170:8170
  openai-api-chatgpt-16k:
    volumes:
      - "./services/openai_api_lm:/src"
      - "./common:/src/common"
    ports:
      - 8167:8167
version: "3.7"
