SERVICE_PORT: 8171
SERVICE_NAME: transformers_lm_ruxglm
PRETRAINED_MODEL_NAME_OR_PATH: dim/xglm-4.5B_ru_v10_epoch_6_step_41141
HALF_PRECISION: 0
EOS_TOKENS: <|endoftext|>,Human
CUDA_VISIBLE_DEVICES: '0'
FLASK_APP: server
