name: dff-fairytale-ru-prompted-skill
endpoints:
- respond
compose:
  env_file:
  - .env_ru
  - .env_secret
  build:
    args:
      SERVICE_PORT: 8174
      SERVICE_NAME: dff_fairytale_ru_prompted_skill
      PROMPT_FILE: common/prompts/fairytale_ru.json
      GENERATIVE_SERVICE_URL: http://transformers-lm-ruxglm:8171/respond
      GENERATIVE_SERVICE_CONFIG: ruxglm_config.json
      GENERATIVE_TIMEOUT: 20
      N_UTTERANCES_CONTEXT: 3
    context: .
    dockerfile: ./skills/dff_template_prompted_skill/Dockerfile
  deploy:
    resources:
      limits:
        memory: 128M
      reservations:
        memory: 128M
  volumes:
  - ./skills/dff_template_prompted_skill:/src
  - ./common:/src/common
  ports:
  - 8174:8174
proxy: null
