name: misheard-asr
endpoints:
- misheard_respond
compose:
  env_file:
  - .env
  build:
    context: .
    dockerfile: ./skills/misheard_asr/Dockerfile
  command: flask run -h 0.0.0.0 -p 8033
  environment:
  - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 128M
      reservations:
        memory: 128M
  volumes:
  - ./skills/misheard_asr:/src
  - ./common:/src/common
  ports:
  - 8033:8033
