services:
  agent:
    volumes:
      - "/cephfs/home/ignatov/artifacts:/output"
    ports:
      - ${AGENT_PORT}:4242
  kbqa:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    environment:
      - CUDA_VISIBLE_DEVICES=5
  text-qa:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    environment:
      - CUDA_VISIBLE_DEVICES=5
  combined-classification:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    environment:
      - CUDA_VISIBLE_DEVICES=8
  mongo:
    command: mongod
    image: mongo:4.0.0
    # # you can use persistent local volume if you need
    # volumes:
    #   - ./venv/data/db_data:/root/data/db
  sentseg:
  dff-intent-responder-skill:
  intent-catcher:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    environment:
      - CUDA_VISIBLE_DEVICES=6
  ner:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
    environment:
      - CUDA_VISIBLE_DEVICES=7
  factoid-qa:
  entity-linking:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    environment:
      - CUDA_VISIBLE_DEVICES=9
  wiki-parser:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
  fact-retrieval:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    environment:
      - CUDA_VISIBLE_DEVICES=7
  entity-detection:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    environment:
      - CUDA_VISIBLE_DEVICES=8
  sentence-ranker:
    volumes:
      - "~/.deeppavlov/cache:/root/.cache"
    environment:
      - CUDA_VISIBLE_DEVICES=9
  property-extraction:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
version: '3.7'
