name: dialog-summarizer
endpoints:
- respond_batch
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8059
      SERVICE_NAME: dialog_summarizer
      PRETRAINED_MODEL_NAME: "knkarthick/MEETING_SUMMARY"
    context: ./services/dialog_summarizer/
  command: flask run -h 0.0.0.0 -p 8059
  environment:
  - CUDA_VISIBLE_DEVICES=0
  - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 4G
      reservations:
        memory: 4G
  volumes:
  - ./services/dialog_summarizer:/src
  ports:
  - 8059:8059
proxy: null
