WAIT_HOSTS: sentseg:8011, badlisted-words:8018, intent-catcher:8014,
  image-captioning:8123, fromage:8069, dff-program-y-skill:8008, dff-intent-responder-skill:8012,
  dff-fromage-image-skill:8070, dff-image-skill:8124, ranking-based-response-selector:8002, dialogpt:8125,
  sentence-ranker:8128
WAIT_HOSTS_TIMEOUT: ${WAIT_TIMEOUT:-1200}
HIGH_PRIORITY_INTENTS: 1
RESTRICTION_FOR_SENSITIVE_CASE: 1
ALWAYS_TURN_ON_ALL_SKILLS: 0
LANGUAGE: EN
FALLBACK_FILE: fallbacks_dream_en.json
