name: dff-food-skill
endpoints:
- respond
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8097
      SERVICE_NAME: dff_food_skill
    context: .
    dockerfile: ./skills/dff_food_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8097
  deploy:
    resources:
      limits:
        memory: 256M
      reservations:
        memory: 256M
  volumes:
  - ./skills/dff_food_skill:/src
  - ./common:/src/common
  ports:
  - 8097:8097
