name: harvesters-maintenance-gobot-skill
endpoints:
- respond
compose:
  build:
    context: skills/harvesters_maintenance_gobot_skill_deepy
  command: gunicorn --workers=1 server:app -b 0.0.0.0:3882 --timeout=1000
  ports:
  - 3882:3882
proxy: null
