name: anthropic-api-claude-v1
endpoints:
- respond
- generate_goals
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8164
      SERVICE_NAME: anthropic_api_claude_v1
      PRETRAINED_MODEL_NAME_OR_PATH: claude-1
      FLASK_APP: server
    context: .
    dockerfile: ./services/anthropic_api_lm/Dockerfile
  command: flask run -h 0.0.0.0 -p 8164
  environment:
  - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 100M
      reservations:
        memory: 100M
  volumes:
  - ./services/anthropic_api_lm:/src
  - ./common:/src/common
  ports:
  - 8164:8164
proxy: null
