SERVICE_PORT: 8172
SERVICE_NAME: dff_dream_persona_ru_prompted_skill
PROMPT_FILE: common/prompts/dream_persona_ru.json
GENERATIVE_SERVICE_URL: http://transformers-lm-ruxglm:8171/respond
GENERATIVE_SERVICE_CONFIG: ruxglm_config.json
GENERATIVE_TIMEOUT: 20
N_UTTERANCES_CONTEXT: 3
