name: dff-science-skill
endpoints:
- respond
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8101
      SERVICE_NAME: dff_science_skill
    context: .
    dockerfile: ./skills/dff_science_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8101
  deploy:
    resources:
      limits:
        memory: 256M
      reservations:
        memory: 256M
  volumes:
  - ./skills/dff_science_skill:/src
  - ./common:/src/common
  ports:
  - 8101:8101
