# С такими volumes удобно дебажить, не нужно пересобирать контейнер каждый раз при изменении кода
services:
  agent:
    volumes:
      - ".:/dp-agent"
    ports:
      - 4242:4242
  ranking-based-response-selector-ru:
    volumes:
      - "./response_selectors/ranking_based_response_selector:/src"
      - "./common:/src/common"
    ports:
      - 8002:8002
  dialogrpt-ru:
    volumes:
      - "./services/dialogrpt_ru:/src"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8122:8122
  transformers-lm-ruxglm:
    volumes:
      - "./services/transformers_lm:/src"
      - "./common:/src/common"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8171:8171
  transformers-lm-rugpt35:
    volumes:
      - "./services/transformers_lm:/src"
      - "./common:/src/common"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8178:8178
  openai-api-chatgpt:
    volumes:
      - "./services/openai_api_lm:/src"
      - "./common:/src/common"
    ports:
      - 8145:8145
  openai-api-davinci3:
    volumes:
      - "./services/openai_api_lm:/src"
      - "./common:/src/common"
    ports:
      - 8131:8131
  openai-api-gpt4:
    volumes:
      - "./services/openai_api_lm:/src"
      - "./common:/src/common"
    ports:
      - 8159:8159
  openai-api-gpt4-32k:
    volumes:
      - "./services/openai_api_lm:/src"
      - "./common:/src/common"
    ports:
      - 8160:8160
  openai-api-chatgpt-16k:
    volumes:
      - "./services/openai_api_lm:/src"
      - "./common:/src/common"
    ports:
      - 8167:8167
  dff-universal-ru-prompted-skill:
    volumes:
      - "./skills/dff_universal_prompted_skill:/src"
      - "./common:/src/common"
    ports:
      - 8161:8161

version: "3.7"
