name: robot-notifications
endpoints:
- check
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8036
      SERVICE_NAME: robot_notifications
      FLASK_APP: server
    context: .
    dockerfile: ./services/robot_notifications/Dockerfile
  command: flask run -h 0.0.0.0 -p 8036
  environment:
  - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 100M
      reservations:
        memory: 100M
  volumes:
  - ./services/robot_notifications:/src
  - ./common:/src/common
  ports:
  - 8036:8036
proxy: null
